---
argument_specs:
  main:
    short_description: "Arguments for the onboard role."
    options:
      tenant:
        type: "string"
        required: true
        description:
          - The tenant name
