- name: Test webhook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print data received via webhook
      ansible.builtin.debug:
        msg: "Received data: {{ awx_webhook_payload }}"
